USE SEDC

ALTER TABLE Products
ADD CONSTRAINT DF_Product_Weight
DEFAULT 100 FOR [Weight]

ALTER TABLE Products
WITH CHECK
ADD CONSTRAINT CHK_Products_price
CHECK (Price >=0)

ALTER TABLE Products
WITH CHECK
ADD CONSTRAINT UC_Code
UNIQUE (Code)

ALTER TABLE Products
ADD CONSTRAINT DF_Products_Price
DEFAULT 1 FOR Price

ALTER TABLE Products
WITH CHECK
ADD CONSTRAINT CHK_Products_Price_Cost
CHECK (Price <= Cost*2)

ALTER TABLE Products
WITH CHECK
ADD CONSTRAINT UC_Name
UNIQUE ([Name])

