USE SEDC

ALTER TABLE BusinessEntities
ADD PRIMARY KEY (Id)

ALTER TABLE Customers
ADD PRIMARY KEY (Id)

ALTER TABLE Employees
ADD PRIMARY KEY (Id)

ALTER TABLE OrderDetails
ADD PRIMARY KEY (Id)

ALTER TABLE Orders
ADD PRIMARY KEY (Id)

ALTER TABLE Products
ADD PRIMARY KEY (Id)